namespace Mhodume;

/// <summary>
/// What the game calls each level, as against what the file is called.
///
/// The save file keys times by level asset name — Gold_ConaptProject04 — and
/// the game's own menu shows conapt04. Some are not guessable at all:
/// Gold_fastlife02 is "admin", Gold_onlyup is "kreedz", Gold_test00 is
/// "mucuslife00". Showing the file name meant showing something no player
/// recognises.
///
/// Generated by tools/genmapnames.py from DA_MapList inside the game's pak,
/// which is where the menu reads it from. Baked in because the app cannot open
/// the pak at runtime: that needs Oodle and a copy of the game.
/// </summary>
public static class MapNames
{
    /// <summary>Level asset name to the name players see, and its ghost-link code.</summary>
    private static readonly Dictionary<string, (string Name, string Code)> Known =
        new(StringComparer.OrdinalIgnoreCase)
    {
        { "Gold_fastlife02",        ("admin", "adm") },
        { "afterwork_00",           ("afterwork00", "aft00") },
        { "Gold_Apogee_00",         ("apogee00", "apo00") },
        { "Gold_Apogee_01",         ("apogee01", "apo01") },
        { "Gold_Apogee_02",         ("apogee02", "apo02") },
        { "Gold_Atago",             ("atago", "ata") },
        { "Gold_bajareverse",       ("bajareverse", "baj") },
        { "Demo00_Conapt00",        ("conapt00", "con00") },
        { "conapt00_inbounds",      ("conapt00_inbounds", "cona") },
        { "Gold_ConaptProject04",   ("conapt04", "con04") },
        { "Gold_ConaptProject05",   ("conapt05", "con05") },
        { "Gold_Conapt05_lightsout",("conapt05_lightsout", "conap") },
        { "Gold_ConaptProject06",   ("conapt06", "con06") },
        { "Gold_ConaptProject08",   ("conapt08", "con08") },
        { "Gold_ConaptProject09",   ("conapt09", "con09") },
        { "Demo02_Fastlife00",      ("conaptend", "con") },
        { "Gold_Credits00",         ("credits", "cre") },
        { "Demo10_Dam",             ("dam", "dam") },
        { "Gold_daurade",           ("daurade", "dau") },
        { "Gold_dhust_02",          ("dhust02", "dhu02") },
        { "Gold_dreamland",         ("dreamland", "dre") },
        { "Gold_EasyLife06",        ("easylife06", "eas06") },
        { "Gold_Foire",             ("foire", "foi") },
        { "Gold_fastlife_B",        ("fragment", "fra") },
        { "Gold_garbek00",          ("garbek00", "gar00") },
        { "Gold_GironStraat",       ("gironstraat", "gir") },
        { "Gold_jetboil00",         ("jetboil00", "jet00") },
        { "Gold_joan00",            ("joan00", "joa00") },
        { "Gold_test02",            ("jungle01", "jun01") },
        { "Gold_test04",            ("jungle02", "jun02") },
        { "Gold_knopf",             ("knopf", "kno") },
        { "Gold_onlyup",            ("kreedz", "kre") },
        { "Gold_LaCiudadBaja",      ("laciudadbaja", "lac") },
        { "MainMenu",               ("Main Menu", "") },
        { "Gold_Mechanisms01",      ("mechanisms01", "mec01") },
        { "Gold_Mechanisms02",      ("mechanisms02", "mec02") },
        { "Gold_Mechanisms03",      ("mechanisms03", "mec03") },
        { "Gold_test00",            ("mucuslife00", "muc00") },
        { "Gold_test01",            ("mucuslife01", "muc01") },
        { "Gold_test03",            ("mucuslife03", "muc03") },
        { "Gold_test07",            ("mucuslife07", "muc07") },
        { "Gold_nightlife",         ("nightlife", "nig") },
        { "ConaptProject00",        ("og_conapt", "ogc") },
        { "Gold_OpenOffice_00",     ("openoffice00", "ope00") },
        { "Gold_OpenOffice_01_alt", ("openoffice01", "ope01") },
        { "Gold_Ozempic_01",        ("ozempic01", "oze01") },
        { "Gold_Ozempic_06",        ("ozempic06", "oze06") },
        { "Gold_Ozempic_08",        ("ozempic08", "oze08") },
        { "Gold_pirouette",         ("pirouette", "pir") },
        { "Gold_Portokalopita_02",  ("portokalopita02", "por02") },
        { "Gold_racetrack",         ("racetrack00", "rac00") },
        { "Gold_roseau",            ("roseau00", "ros00") },
        { "Demo03_Sewers00",        ("sewers00", "sew00") },
        { "Demo04_Sewers01",        ("sewers01", "sew01") },
        { "Demo03_Sewers02",        ("sewers02", "sew02") },
        { "Demo07_Showers00",       ("showers00", "sho00") },
        { "Gold_StreetLife",        ("streetlife00", "str00") },
        { "Gold_StreetLife01",      ("streetlife01", "str01") },
        { "Gold_StreetLife02",      ("streetlife02", "str02") },
        { "Gold_StreetLife03",      ("streetlife03", "str03") },
        { "Gold_tsukuba",           ("tsukuba", "tsu") },
        { "Gold_fastlife00",        ("vestiges", "ves") },
        { "Gold_windfans",          ("windfarm00", "win00") },
        { "Gold_windpipe",          ("windpipe", "win") },
    };

    /// <summary>
    /// The name the game would show. Falls back to the asset name, which is
    /// what a level added after this table was generated will land on.
    /// </summary>
    public static string Display(string? asset) =>
        asset is not null && Known.TryGetValue(asset, out var e) && e.Name.Length > 0
            ? e.Name
            : asset ?? "";

    /// <summary>The short code the game uses in ghost links, or "".</summary>
    public static string Code(string? asset) =>
        asset is not null && Known.TryGetValue(asset, out var e) ? e.Code : "";

    /// <summary>True when the game has a name of its own for this level.</summary>
    public static bool IsKnown(string? asset) =>
        asset is not null && Known.ContainsKey(asset);

    /// <summary>How many levels the table covers.</summary>
    public static int Count => Known.Count;
}
