<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>MhodumeLauncher</AssemblyName>
    <RootNamespace>Mhodume</RootNamespace>
    <Version>0.1.0</Version>
    <Product>Mhodume Launcher</Product>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <ApplicationIcon>assets\mhodume.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="assets\mhodume.ico"/>
    <Resource Include="assets\mhodume-64.png"/>
  </ItemGroup>

</Project>
